name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Check code formatting using prettier
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Mise
        uses: jdx/mise-action@v3

      - name: Check code formatting
        run: mise check-format

  # Lint the codebase with ESLint
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm -r lint

  # Type check the codebase with TypeScript
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma client
        run: NODE_ENV=test pnpm --filter api prisma:generate

      - name: Run type checking for API
        run: pnpm --filter api typecheck

  # Run tests and collect coverage
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: pnpm install

      - name: Setup containers
        run: mise compose-up-dev

      - name: Generate Prisma client
        run: NODE_ENV=test pnpm --filter api prisma:generate

      - name: Run coverage report
        run: pnpm --filter api test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
